### ISSUE TITLE
ASTM technical documentation

### ISSUE THREAD

**Issue by vunb** [iShafayet/node-astm#3]
Hi @iShafayet 

Do you have any documents for understanding or references about `ASTM protocol`? Could you please recommend some for me?

Thank you!

**Comment by iShafayet** [comment]
@vunb I have some manuals directly from manufacturers that explain ASTM rather well. Sadly, I don't have the rights to redistribute them. But you can mail them and they will most likely send you the manuals. 

Here's a rather good one. http://www.horiba.com/medical/products/hematology/abx-pentra-60/abx-pentra-60-details/abx-pentra-60-903/

**Comment by vunb** [comment]
Thank you @iShafayet
